### ISSUE TITLE
Error: Value cannot be null. (Parameter 'input') 

### ISSUE THREAD

**Issue by rnpramasamy** [Azure/semantic-kernel-bot-in-a-box#2]
I updated SearchPlugin to use my Cognitive Search Index. When I ran and tested this bot, I was getting "Value cannot be null. (Parameter 'input')" error.

   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Microsoft.SemanticKernel.Planners.StepwisePlanner.ParseResult(String input)
   at Microsoft.SemanticKernel.Planners.StepwisePlanner.<>c__DisplayClass2_0.<<ExecutePlanAsync>g__GetNextStepAsync|0>d.MoveNext()
   at Microsoft.SemanticKernel.Planners.StepwisePlanner.<ExecutePlanAsync>d__2.MoveNext()
   at Microsoft.SemanticKernel.NativeFunction.<>c.<<GetReturnValueMarshalerDelegate>b__35_4>d.MoveNext()
   at Microsoft.SemanticKernel.NativeFunction.<InvokeAsync>d__18.MoveNext()
   at Microsoft.SemanticKernel.InstrumentedSKFunction.<InvokeWithInstrumentationAsync>d__21.MoveNext()
   at Microsoft.SemanticKernel.InstrumentedSKFunction.<InvokeAsync>d__10.MoveNext()
   at Microsoft.SemanticKernel.Planning.Plan.<InvokeAsync>d__47.MoveNext()
   at Microsoft.SemanticKernel.Kernel.<RunAsync>d__21.MoveNext()
   at Microsoft.BotBuilderSamples.SKBot.<ProcessMessage>d__17.MoveNext() in E:\GitHub\semantic-kernel-bot-in-a-box\src\Bots\SKBot.cs:line 123
   at Microsoft.BotBuilderSamples.StateManagementBot.<OnMessageActivityAsync>d__5.MoveNext() in E:\GitHub\semantic-kernel-bot-in-a-box\src\Bots\StateManagementBot.cs:line 51
   at Microsoft.Bot.Builder.ActivityHandler.<OnTurnAsync>d__0.MoveNext()
   at Microsoft.BotBuilderSamples.StateManagementBot.<OnTurnAsync>d__3.MoveNext() in E:\GitHub\semantic-kernel-bot-in-a-box\src\Bots\StateManagementBot.cs:line 28
   at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext()
   at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__23.MoveNext()

My updated code:
![image](https://github.com/Azure/semantic-kernel-bot-in-a-box/assets/5311453/1524c648-aef2-46d8-8284-5160935d1801)

Please help me to fix this issue.

**Comment by MarcoABCardoso** [comment]
Hello @rnpramasamy, thank you for your interest in the project.

I see you implemented your own search document model SharePointDoc. Is that using the preview SharePoint Indexer? https://learn.microsoft.com/en-us/azure/search/search-howto-index-sharepoint-online

Also, have you been able to run the bot with the DEBUG flag enabled? Any insights into the planners thought process should be helpful in debugging the issue.

**Comment by MarcoABCardoso** [comment]
Closing this issue due to inactivity - please feel free to reopen if needed!
