### ISSUE TITLE
Error on Teams bot

### ISSUE THREAD

**Issue by c-nova** [Azure/semantic-kernel-bot-in-a-box#6]
When I tried to connect to this solution in Teams, I got an error and finished.
I set up a Teams channel and just typed Hello after the first greeting message appeared.

After the system receives the message in Teams, it appears to be giving an error because the URI is NULL when trying to execute the function of file upload.

Bot Message:
The bot encountered an error or bug.
To continue to run this bot, please fix the bot source code.

The error message in the debug console is as follows.

Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Uri..ctor(String uriString)
   at Microsoft.BotBuilderSamples.SKBot.HandleFileUpload(ConversationData conversationData, ITurnContext`1 turnContext) in /Users/c-nova/Library/CloudStorage/OneDrive-Microsoft/Sources/demo/OpenAI/semantic-kernel-bot-in-a-box/src/Bots/SKBot.cs:line 122
   at Microsoft.BotBuilderSamples.SKBot.ProcessMessage(ConversationData conversationData, ITurnContext`1 turnContext) in /Users/c-nova/Library/CloudStorage/OneDrive-Microsoft/Sources/demo/OpenAI/semantic-kernel-bot-in-a-box/src/Bots/SKBot.cs:line 97
   at Microsoft.BotBuilderSamples.StateManagementBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /Users/c-nova/Library/CloudStorage/OneDrive-Microsoft/Sources/demo/OpenAI/semantic-kernel-bot-in-a-box/src/Bots/StateManagementBot.cs:line 53
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.StateManagementBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in /Users/c-nova/Library/CloudStorage/OneDrive-Microsoft/Sources/demo/OpenAI/semantic-kernel-bot-in-a-box/src/Bots/StateManagementBot.cs:line 30
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

**Comment by MarcoABCardoso** [comment]
Hello @c-nova!

It seems Teams in currently incompatible with the latest version of the Upload plugin.
I have a fix ready and am working to push this out later today as soon as validations are complete.

Thank you for pointing out this error and for your interest in the project!

Marco

**Comment by c-nova** [comment]
Hi @MarcoABCardoso !

My colleage found the mitigate plan for this issue.

public override async Task<string> ProcessMessage(ConversationData conversationData, ITurnContext<IMessageActivity> turnContext)
        {
            // Handle file uploads
            if (turnContext.Activity.Attachments?.Any(x => x.ContentUrl != null) == true)
            {
                if (!_config.GetValue<string>("DOCINTEL_API_ENDPOINT").IsNullOrEmpty())
                    return await HandleFileUpload(conversationData, turnContext);
                else
                    return "Document upload not supported as no Document Intelligence endpoint was provided";
            }

Origianl code is wrote with "if (turnContext.Activity.Attachments?.Count > 0)", new one is changed to "if (turnContext.Activity.Attachments?.Any(x => x.ContentUrl != null) == true)".
It seems mitigate miss route to file upload handler, but Teams upload is not to be able.

I hope you find it helpful.

**Comment by MarcoABCardoso** [comment]
Hey @c-nova!

There's an update out now to specifically target pdf attachments, as they're the only ones supported by the UploadPlugin.
Please drop a comment if you're still having issues after the latest commit as of today.

Thank you!

**Comment by c-nova** [comment]
@MarcoABCardoso ,
The issue wad resolved because of new one.
Thank you so much!
